ref: rocky/${basearch}/ostree/${stream}
rojig:
  name: rocky-ostree
  summary: "Rocky Linux OSTree ${stream}"
  license: MIT

add-commit-metadata:
  rocky-core.stream: ${stream}

include:
  - rocky-coreos-base.yaml

conditional-include:
  - if: basearch != "s390x"
    # And remove some cruft from grub2
    include: grub2-removals.yaml

ostree-layers:
  - overlay/15fcos

automatic-version-prefix: "${releasever}.<date:%Y%m%d>.dev"
mutate-os-release: "${releasever}"

remove-from-packages:
  # Drop NetworkManager support for ifcfg files, see also corresponding
  # overlay.d/14NetworkManager-plugins
  - [NetworkManager, /usr/lib64/NetworkManager/.*/libnm-settings-plugin-ifcfg-rh.so]
  # Drop some buggy sysusers fragments which do not match static IDs allocation:
  # https://bugzilla.redhat.com/show_bug.cgi?id=2105177
  # - [dbus-common, /usr/lib/sysusers.d/dbus.conf]

remove-files:
  # We don't ship man(1) or info(1)
  - usr/share/info
  - usr/share/man
  # Drop text docs too
  - usr/share/doc

# Things we don't expect to ship on the host.  We currently
# have recommends: false so these could only come in via
# hard requirement, in which case the build will fail.
exclude-packages:
  - python
  - python2
  - python2-libs
  # - python3
  # - python3-libs
  - perl
  - perl-interpreter
  - nodejs
  - dnf
  - grubby
  - cowsay  # Just in case
  # Let's make sure initscripts doesn't get pulled back in
  # https://github.com/coreos/fedora-coreos-tracker/issues/220#issuecomment-611566254
  - initscripts
  # For (datacenter/cloud oriented) servers, we want to see the details by default.
  # https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HSMISZ3ETWQ4ETVLWZQJ55ARZT27AAV3/
  - plymouth